version: '3'

services:
  backend:
    build: ./backend/
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
  frontend:
    build: ./frontend/
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/opt/app
  postgres:
    image: "postgres:alpine"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
volumes:
  dbdata: