version: '3'

services:
  backend:
    build: ./backend/
    environment:
      - DATABASE_URL=sqlite:///devdb.db
      - FLASK_APP_SECRET_KEY=devkey
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend/
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/opt/app