[Settings]
ID = "infallible-babbage-fd9286"

[build]
    base    = "frontend/"
    publish = "frontend/build/"
    command = "yarn run build-netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200