"""empty message

Revision ID: 99a499d723ed
Revises: 61ba9f2934e6
Create Date: 2018-11-21 10:51:36.416184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a499d723ed' 
down_revision = '61ba9f2934e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('debt', sa.Column('pool_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'debt', 'pool', ['pool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debt', type_='foreignkey')
    op.drop_column('debt', 'pool_id')
    op.drop_table('pool')
    # ### end Alembic commands ###
